name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build -r --verbose
    - name: Run tests
      run: cargo test --verbose

    - name: release-please-action
    # You may pin to the exact commit or the version.
    # uses: googleapis/release-please-action@f0145e31b50c56905571d69a63bbe997c0ce6dd1
      uses: googleapis/release-please-action@v3.1.2
      with:
        # what type of release is this, one of (ruby, python, node, terraform-module)
        release-type: rust
      
          
